# Generated by Django 5.1.1 on 2024-11-11 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('上半身', '上半身'), ('下半身', '下半身'), ('腹部', '腹部'), ('二の腕', '二の腕'), ('太もも', '太もも')], max_length=10)),
                ('difficulty_level', models.CharField(choices=[('初級', '初級'), ('中級', '中級'), ('上級', '上級')], max_length=10)),
                ('calories_burned', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('video_url', models.URLField()),
                ('instructions', models.TextField()),
                ('target_muscled', models.TextField()),
                ('body_parts', models.TextField()),
                ('equipments', models.TextField()),
                ('secondary_muscles', models.TextField()),
            ],
        ),
    ]
