# Generated by Django 5.1.1 on 2024-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_id',
            field=models.CharField(default='default_id', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(default='default_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='body_parts',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipments',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscled',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
