# Generated by Django 5.1.1 on 2024-11-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_exercise_exercise_id_exercise_gif_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_parts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='target_muscled',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
