# Generated by Django 5.1.1 on 2024-11-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0003_alter_exercise_body_parts_alter_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
    ]
